name: GitHub Actions Workflow with PNPM cache

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v2
      with:
        version: 6.32.9

    - uses: actions/setup-node@v4
      with:
        node-version: '14'
        cache: 'pnpm'
        
    - name: Install PNPM
      run: npm install -g pnpm

    - name: Verify PNPM installation
      run: pnpm --version

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm run build
