name: basic-dev-setup

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Verify pnpm installation
      run: pnpm --version

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm run build
